name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.emacs_version == 'snapshot'}}

    strategy:
      matrix:
        emacs_version: ['29.1', '29.2', 'snapshot']

    steps:
    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eask
      uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Run CI
      run: make ci
